use Projeto

-- Exercicio 1
SELECT * 
FROM MATRICULA as M
	INNER JOIN ALUNO as A 
ON 
	A.cpf = M.cpf_aluno;
-- Exercicio 2
SELECT * FROM CURSO AS C, DISCIPLINA AS D;
SELECT * FROM DISCIPLINA
SELECT * FROM COMPOE
SELECT * FROM CURSO;

SELECT DIS.nome FROM COMPOE AS COM
INNER JOIN DISCIPLINA AS DIS 


SELECT  



ON
	DIS.codigo = COM.codigo_disc
INNER JOIN CURSO AS CUR
ON 
	CUR.codigo = 
;

SELECT CURSO.nome AS CURSO, DISCIPLINA.nome AS DISCIPLINA
FROM CURSO
JOIN DEPARTAMENTO ON CURSO.codigo = codigo_dpto.codigo
JOIN DISCIPLINA ON codigo_dpto.codigo = DISCIPLINA.nome;

-- Exercicio 3
SELECT ALUNO.nome AS ALUNO, DISCIPLINA.nome AS DISCIPLINA
FROM ALUNO 
JOIN MATRICULA ON ALUNO.cpf = MATRICULA.cpf_aluno
JOIN nome ON MATIRCULA.codigo_curso = nome.codigo_curso
JOIN DISCIPLINA ON nome.codigo = DISCIPLINA.codigo;

-- Exercicio 4
SELECT PROFESSOR.nome AS PROFESSOR, DISCIPLINA.nome AS DISCIPLINA
FROM PROFESSOR 
JOIN DISCIPLINA ON PROFESSOR.matricula = DISCIPLINA.matricula_prof;